### ISSUE TITLE
RSS Link not working

### ISSUE THREAD

**Issue by clemera** [casouri/casouri.github.io#2]
Hi, 

The RSS link of your blog does not work:

https://archive.casouri.co.uk/note/index.xml

**Comment by casouri** [comment]
Thank clemera, and sorry for not replying you. I've read your issue right after you posted it and tried to fix it ever since, but now I still haven't got a good result. I fear it would be rude to not get back to you for too long, thus this reply. I'll post back again once I got it working.

**Comment by clemera** [comment]
No problem, just wanted to let you know in case you did not knew it already.

**Comment by casouri** [comment]
Now I proudly announce that the RSS is working now. (Applause) Thank you, thank you. My pleasure.
